// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VatEvidence.Infrastructure.Persistence;

#nullable disable

namespace VatEvidence.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260202200000_AddEvidenceSequenceAndIdempotency")]
    partial class AddEvidenceSequenceAndIdempotency
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VatEvidence.Domain.EvidenceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CapturedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_utc");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<int>("EvidenceType")
                        .HasColumnType("integer")
                        .HasColumnName("evidence_type");

                    b.Property<string>("PrevRecordHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("prev_record_hash");

                    b.Property<string>("RecordHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("record_hash");

                    b.Property<string>("SourceRef")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("source_ref");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<JsonDocument>("ValueRaw")
                        .HasColumnType("jsonb")
                        .HasColumnName("value_raw");

                    b.HasKey("Id")
                        .HasName("pk_evidence_records");

                    b.HasIndex("TransactionId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_evidence_records_tx_sequence");

                    b.HasIndex("TransactionId", "EvidenceType", "SourceRef")
                        .IsUnique()
                        .HasDatabaseName("ux_evidence_records_tx_type_source");

                    b.HasIndex("TransactionId", "CapturedUtc")
                        .HasDatabaseName("ix_evidence_records_transaction_id_captured_utc");

                    b.ToTable("evidence_records", (string)null);
                });

            // Additional entities would be here (skipped for brevity in designer file)
#pragma warning restore 612, 618
        }
    }
}
