// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VatEvidence.Infrastructure.Persistence;

#nullable disable

namespace VatEvidence.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260209132509_AddRestrictDeleteOnEvidenceRecords")]
    partial class AddRestrictDeleteOnEvidenceRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VatEvidence.Domain.EvidenceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CapturedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_utc");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<int>("EvidenceType")
                        .HasColumnType("integer")
                        .HasColumnName("evidence_type");

                    b.Property<string>("PrevRecordHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("prev_record_hash");

                    b.Property<string>("RecordHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("record_hash");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<string>("SourceRef")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("source_ref");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<JsonDocument>("ValueRaw")
                        .HasColumnType("jsonb")
                        .HasColumnName("value_raw");

                    b.HasKey("Id")
                        .HasName("pk_evidence_records");

                    b.HasIndex("TransactionId", "CapturedUtc")
                        .HasDatabaseName("ix_evidence_records_transaction_id_captured_utc");

                    b.HasIndex("TransactionId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_evidence_records_tx_sequence");

                    b.HasIndex("TransactionId", "EvidenceType", "SourceRef")
                        .IsUnique()
                        .HasDatabaseName("ux_evidence_records_tx_type_source");

                    b.ToTable("evidence_records", (string)null);
                });

            modelBuilder.Entity("VatEvidence.Domain.Export", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("file_hash");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("file_path");

                    b.Property<DateTimeOffset>("RangeFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("range_from");

                    b.Property<DateTimeOffset>("RangeTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("range_to");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_exports");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_exports_workspace_id");

                    b.ToTable("exports", (string)null);
                });

            modelBuilder.Entity("VatEvidence.Domain.ProviderConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Mode")
                        .HasColumnType("integer")
                        .HasColumnName("mode");

                    b.Property<int>("Provider")
                        .HasColumnType("integer")
                        .HasColumnName("provider");

                    b.Property<string>("WebhookSecret")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("webhook_secret");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_provider_connections");

                    b.HasIndex("WorkspaceId", "Provider", "Mode")
                        .IsUnique()
                        .HasDatabaseName("ix_provider_connections_workspace_id_provider_mode");

                    b.ToTable("provider_connections", (string)null);
                });

            modelBuilder.Entity("VatEvidence.Domain.ProviderEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<int>("Mode")
                        .HasColumnType("integer")
                        .HasColumnName("mode");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payload_hash");

                    b.Property<JsonDocument>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<int>("ProcessingStatus")
                        .HasColumnType("integer")
                        .HasColumnName("processing_status");

                    b.Property<int>("Provider")
                        .HasColumnType("integer")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_event_id");

                    b.Property<DateTimeOffset>("ReceivedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_provider_events");

                    b.HasIndex("WorkspaceId", "Provider", "Mode", "ProviderEventId")
                        .IsUnique()
                        .HasDatabaseName("ix_provider_events_workspace_id_provider_mode_provider_event_id");

                    b.ToTable("provider_events", (string)null);
                });

            modelBuilder.Entity("VatEvidence.Domain.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("customer_email");

                    b.Property<int>("Mode")
                        .HasColumnType("integer")
                        .HasColumnName("mode");

                    b.Property<int>("Provider")
                        .HasColumnType("integer")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderChargeId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_charge_id");

                    b.Property<string>("ProviderTransactionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_transaction_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("status_reason");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("WorkspaceId", "Provider", "Mode", "ProviderTransactionId")
                        .IsUnique()
                        .HasDatabaseName("ix_transactions_workspace_id_provider_mode_provider_transactio");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("VatEvidence.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("VatEvidence.Domain.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("VatEvidence.Domain.WorkspaceUser", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("WorkspaceId", "UserId")
                        .HasName("pk_workspace_users");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_workspace_users_user_id");

                    b.ToTable("workspace_users", (string)null);
                });

            modelBuilder.Entity("VatEvidence.Domain.EvidenceRecord", b =>
                {
                    b.HasOne("VatEvidence.Domain.Transaction", "Transaction")
                        .WithMany("EvidenceRecords")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_evidence_records_transactions_transaction_id");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("VatEvidence.Domain.Export", b =>
                {
                    b.HasOne("VatEvidence.Domain.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exports_workspaces_workspace_id");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("VatEvidence.Domain.ProviderConnection", b =>
                {
                    b.HasOne("VatEvidence.Domain.Workspace", "Workspace")
                        .WithMany("ProviderConnections")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_provider_connections_workspaces_workspace_id");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("VatEvidence.Domain.ProviderEvent", b =>
                {
                    b.HasOne("VatEvidence.Domain.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_provider_events_workspaces_workspace_id");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("VatEvidence.Domain.Transaction", b =>
                {
                    b.HasOne("VatEvidence.Domain.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_workspaces_workspace_id");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("VatEvidence.Domain.WorkspaceUser", b =>
                {
                    b.HasOne("VatEvidence.Domain.User", "User")
                        .WithMany("Workspaces")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_users_users_user_id");

                    b.HasOne("VatEvidence.Domain.Workspace", "Workspace")
                        .WithMany("Users")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_users_workspaces_workspace_id");

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("VatEvidence.Domain.Transaction", b =>
                {
                    b.Navigation("EvidenceRecords");
                });

            modelBuilder.Entity("VatEvidence.Domain.User", b =>
                {
                    b.Navigation("Workspaces");
                });

            modelBuilder.Entity("VatEvidence.Domain.Workspace", b =>
                {
                    b.Navigation("ProviderConnections");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
